# Generated by Django 2.2 on 2020-06-21 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_text', models.CharField(max_length=30, verbose_name='试卷标题')),
                ('pub_date', models.DateTimeField(verbose_name='发布日期')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('idcard', models.CharField(max_length=128, unique=True, verbose_name='学号')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='分数')),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsystem.Paper')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsystem.User')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
                'ordering': ['paper_id', '-score'],
            },
        ),
        migrations.CreateModel(
            name='SC_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SC_text', models.CharField(max_length=200, verbose_name='单选题内容')),
                ('SC_solution', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, verbose_name='单选题答案')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsystem.Paper')),
            ],
            options={
                'verbose_name': '单选题',
                'verbose_name_plural': '单选题',
            },
        ),
        migrations.CreateModel(
            name='SC_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_symbol', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, verbose_name='选项符号')),
                ('choice_text', models.CharField(max_length=200, verbose_name='选项内容')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsystem.SC_question')),
            ],
            options={
                'verbose_name': '单选题选项',
                'verbose_name_plural': '单选题选项',
            },
        ),
        migrations.CreateModel(
            name='MC_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MC_text', models.CharField(max_length=200, verbose_name='多选题内容')),
                ('MC_solution', models.CharField(max_length=6, verbose_name='多选题答案')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsystem.Paper')),
            ],
            options={
                'verbose_name': '多选题',
                'verbose_name_plural': '多选题',
            },
        ),
        migrations.CreateModel(
            name='MC_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_symbol', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, verbose_name='选项符号')),
                ('choice_text', models.CharField(max_length=200, verbose_name='选项内容')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsystem.MC_question')),
            ],
            options={
                'verbose_name': '多选题选项',
                'verbose_name_plural': '多选题选项',
            },
        ),
        migrations.CreateModel(
            name='Blank_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_text', models.CharField(max_length=200, verbose_name='填空题内容')),
                ('blank_solution', models.CharField(max_length=20, verbose_name='填空题答案')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsystem.Paper')),
            ],
            options={
                'verbose_name': '填空题',
                'verbose_name_plural': '填空题',
            },
        ),
    ]
