# Generated by Django 3.0.7 on 2020-06-22 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_choice',
            name='paper',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='testsystem.Paper'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sc_choice',
            name='paper',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='testsystem.Paper'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
    ]
