# Generated by Django 3.0.7 on 2020-06-20 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0002_auto_20200620_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_text',
            field=models.CharField(max_length=30, verbose_name='试卷标题'),
        ),
    ]
