# Generated by Django 3.0.7 on 2020-07-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0003_auto_20200622_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='answer',
            field=models.CharField(default='none', max_length=3072, verbose_name='答题卡'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='分数'),
        ),
    ]
