# Generated by Django 3.0.7 on 2020-07-02 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0004_auto_20200702_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='限时'),
            preserve_default=False,
        ),
    ]
