# Generated by Django 3.0.7 on 2020-07-03 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0005_paper_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='答题计时'),
            preserve_default=False,
        ),
    ]
