# Generated by Django 3.0.7 on 2020-07-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0006_score_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='F:\\开发源码\\python\\OnlineExerciseTest\\upload/', verbose_name='文件')),
                ('name', models.CharField(max_length=200, verbose_name='文件名称')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'db_table': 'test_file',
            },
        ),
    ]
