# Generated by Django 3.0.7 on 2020-07-06 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0007_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='限时'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='F:\\开发源码\\python\\OnlineExerciseTest\\upload/', verbose_name='上传试卷'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=200, verbose_name='试卷名称'),
        ),
    ]
