# Generated by Django 3.1 on 2020-08-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0008_auto_20200706_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blank_question',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='分值'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='upload', verbose_name='上传试卷'),
        ),
        migrations.AlterField(
            model_name='mc_question',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='分值'),
        ),
        migrations.AlterField(
            model_name='sc_question',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='分值'),
        ),
    ]
