# Generated by Django 3.0.7 on 2020-08-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0008_auto_20200706_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blank_question',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='分值'),
        ),
        migrations.AlterField(
            model_name='mc_question',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='分值'),
        ),
        migrations.AlterField(
            model_name='sc_question',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='分值'),
        ),
    ]
