# Generated by Django 3.0.7 on 2020-08-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0009_auto_20200807_0426'),
        ('testsystem', '0009_auto_20200807_1247'),
    ]

    operations = [
    ]
